---

- name: Asking for role variable {{ rolevar.name }}
  pause:
    prompt: |
      {{ '~'|horizontalize }}

      {{ rolevar.question }}

      {% if rolevar.name in hostvars[inventory_hostname] %}
      {{ ('Currently: ' + rolevar.name + '="' + hostvars[inventory_hostname][rolevar.name] + '"') }}
      {% endif -%}

      {{ '~'|horizontalize }}
      {% if rolevar.default|default(false) %}
      default='{{ rolevar.default }}'
      {% endif -%}

      Your answer will be saved on the host (path to be annouced).

      We won't ask you again for {{ inventory_hostname }}, but you can see this again using
      forceask={{ rolevar.name }} or forceask=all or change it directly in the role's .fact file.

      Enter two single quotes for blank value as such: ''
      {% if rolevar.name in hostvars[inventory_hostname] %}
      Press Enter (leave blank) to leave CURRENT value "{{ hostvars[inventory_hostname][rolevar.name] }}"
      {% elif rolevar.default|default(false) %}
      Press Enter (leave blank) to leave default value "{{ rolevar.default }}"
      {% endif -%}
      {% if 'choices' in rolevar %}
      Choices:
      {% for key, value in rolevar.choices.items() %}
      - {{ key }}: {{ value }}
      {% endfor %}
      {% endif %}
      <CTRL+C> <A>    To abort play
      {% if 'regexp' in rolevar %}
      Your input has to validate against: {{ rolevar.regexp }}
      {%- endif %}
  register: prompt
  until: |
    (
      prompt.user_input
      and prompt.user_input|validate(rolevar.regexp|default(''))
    )
    or 'default' in rolevar
    or rolevar.name in hostvars[inventory_hostname]
  delay: 0.00001
  retries: 20

- name: Setting choice
  set_fact: {'{{ rolevar.name }}': "{{ rolevar.choices[prompt.user_input]}}"}
  when: prompt.user_input and prompt.user_input in rolevar.get('choices', {})

- name: Setting {{ rolevar.name }}={{ prompt.user_input }}
  set_fact: {'{{ rolevar.name }}': "{% if prompt.user_input != \"''\" %}{{ prompt.user_input }}{% endif %}"}
  when: prompt.user_input and ('choices' not in rolevar or prompt.user_input not in rolevar.choices)

- name: Setting {{ rolevar.name }}={{ rolevar.default }}
  set_fact: {'{{ rolevar.name }}': '{{ rolevar.default }}'}
  when: "'default' in rolevar and not prompt.user_input"
